spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/qnwb
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qnbbs.obj
---
#测试环境配置
spring:
  profiles: test
server:
  port: 8080
---
#生产环境配置
spring:
  profiles: dev
server:
  port: 8082